name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: kakd1313/bu-web-exhibition
          stage: main
          yaml: |
            name: bu-web-exhibition
            app: web
            options:
              docbase: /
              spa: false
              nodeversion: "16"
              indexpage: index2.html
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}